"""Screening universes.

CORE  = ~57 hand-picked durable compounders (fast interactive scans).
FULL  = ~220 quality large/mid-caps across every sector (the weekly job scans
        this). It's a *hunting ground*, not a buy list — the model still decides
        what's attractive at today's price. Delisted/renamed tickers are skipped
        gracefully during a scan, so occasional staleness is harmless.

Grouped by sector for readability; FULL is the de-duped flatten of SECTORS.
"""
from __future__ import annotations

CORE = [
    "AAPL", "MSFT", "GOOGL", "META", "NVDA", "ADBE", "CRM", "ORCL", "CSCO", "TXN",
    "AVGO", "QCOM", "INTU", "ACN",
    "KO", "PEP", "PG", "COST", "WMT", "MDLZ", "CL", "MCD", "SBUX", "NKE",
    "JNJ", "UNH", "ABBV", "MRK", "PFE", "LLY", "TMO", "ABT", "ISRG", "MDT",
    "V", "MA", "BRK-B", "JPM", "SPGI", "MCO", "BLK", "AXP",
    "HON", "UNP", "CAT", "DE", "LMT", "RTX", "LIN", "ADP", "TDG", "WM",
    "HD", "LOW", "DIS", "NFLX", "TJX",
]

SECTORS: dict[str, list[str]] = {
    "Technology & Semiconductors": [
        "AAPL", "MSFT", "GOOGL", "META", "NVDA", "AVGO", "ORCL", "ADBE", "CRM",
        "CSCO", "ACN", "TXN", "QCOM", "AMD", "INTU", "NOW", "AMAT", "LRCX", "KLAC",
        "ADI", "MU", "SNPS", "CDNS", "ANET", "PANW", "FTNT", "CRWD", "ROP", "MSI",
        "APH", "TEL", "IT", "GLW", "DELL", "WDAY", "ADSK", "INTC",
    ],
    "Internet, Media & Communications": [
        "AMZN", "NFLX", "DIS", "CMCSA", "TMUS", "VZ", "T", "EA", "TTWO",
        "UBER", "ABNB", "BKNG",
    ],
    "Consumer Staples": [
        "KO", "PEP", "PG", "COST", "WMT", "MDLZ", "CL", "KMB", "GIS", "KHC",
        "HSY", "STZ", "MO", "PM", "KDP", "SYY", "MNST", "CHD", "CLX", "TGT", "DG",
    ],
    "Consumer Discretionary": [
        "MCD", "SBUX", "NKE", "HD", "LOW", "TJX", "ROST", "MAR", "HLT", "YUM",
        "CMG", "ORLY", "AZO", "LULU", "GM", "APTV", "GPC",
    ],
    "Healthcare": [
        "JNJ", "UNH", "LLY", "ABBV", "MRK", "PFE", "TMO", "ABT", "DHR", "BMY",
        "AMGN", "MDT", "ISRG", "GILD", "CI", "CVS", "ELV", "ZTS", "BDX", "SYK",
        "BSX", "REGN", "VRTX", "HCA", "MCK", "IDXX", "EW", "IQV",
    ],
    "Financials": [
        "BRK-B", "JPM", "V", "MA", "BAC", "WFC", "MS", "GS", "SPGI", "MCO", "BLK",
        "AXP", "C", "SCHW", "CB", "PGR", "MMC", "AON", "ICE", "CME", "USB", "PNC",
        "COF", "AIG", "MET", "TRV",
    ],
    "Industrials": [
        "HON", "UNP", "CAT", "DE", "LMT", "RTX", "GE", "MMM", "UPS", "FDX", "EMR",
        "ETN", "ITW", "PH", "GD", "NOC", "CSX", "NSC", "WM", "RSG", "ADP", "PAYX",
        "TT", "CMI", "ROK", "TDG", "LHX", "FAST", "ODFL",
    ],
    "Energy": [
        "XOM", "CVX", "COP", "SLB", "EOG", "MPC", "PSX", "VLO", "WMB", "OKE",
    ],
    "Materials": [
        "LIN", "APD", "SHW", "ECL", "FCX", "NEM", "NUE", "DOW", "PPG", "VMC", "MLM",
    ],
    "Utilities": [
        "NEE", "DUK", "SO", "D", "AEP", "EXC", "SRE", "XEL",
    ],
    "Real Estate": [
        "PLD", "AMT", "EQIX", "CCI", "PSA", "O", "SPG", "WELL",
    ],
}

# De-duped flatten, preserving order.
FULL = list(dict.fromkeys(t for names in SECTORS.values() for t in names))

# LARGE (~900, S&P 500 + S&P 400 ≈ Russell 1000) is generated by
# tools/refresh_universe.py. Fall back to FULL if it hasn't been generated.
try:
    from large_universe import LARGE  # type: ignore
except Exception:  # noqa: BLE001
    LARGE = list(FULL)


def peers_of(ticker: str, limit: int = 8) -> list[str]:
    """Same-sector peers from the curated SECTORS map (instant, no fetching)."""
    ticker = ticker.strip().upper()
    for names in SECTORS.values():
        if ticker in names:
            return [t for t in names if t != ticker][:limit]
    return []


def get(scope: str = "full") -> list[str]:
    """Return a universe by name: 'core' (~57), 'full' (~207), 'large' (~900), or
    'all' (~5,000 raw US-listed — meant to be passed through a market-cap floor
    before scanning)."""
    scope = (scope or "").lower()
    if scope == "core":
        return list(CORE)
    if scope == "large":
        return list(LARGE)
    if scope == "all":
        import all_us_symbols
        return list(all_us_symbols.ALL_US)
    return list(FULL)
