#!/usr/bin/env python3
"""Regenerate the large-cap screening universe (S&P 500 + S&P 400 ≈ Russell 1000).

The literal Russell 1000 membership is only published by iShares (IWB), which
bot-blocks direct CSV downloads. The S&P 500 + S&P 400 (mid-cap) union — the
"S&P 900" — is a current, freely parseable, large+mid-cap set that tracks the
Russell 1000 closely (both are large/mid-cap US equity). We pull it from
Wikipedia's constituent tables and write backend/large_universe.py.

Run occasionally to refresh (index membership drifts):
    .venv/bin/python tools/refresh_universe.py
"""
from __future__ import annotations

import re
from pathlib import Path

from curl_cffi import requests as cr

PAGES = {
    "sp500": "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies",
    "sp400": "https://en.wikipedia.org/wiki/List_of_S%26P_400_companies",
}
OUT = Path(__file__).resolve().parent.parent / "backend" / "large_universe.py"


def tickers(session, url: str) -> list[str]:
    html = session.get(url, timeout=30).text
    raw = re.findall(r'(?:Nyse|Nasdaq)Symbol"[\s\S]{0,90}?"wt":"([A-Z][A-Z.]{0,6})"', html)
    # Yahoo uses '-' as the class separator (BRK.B -> BRK-B).
    return [t.replace(".", "-") for t in raw]


def main():
    s = cr.Session(impersonate="chrome")
    sp500 = tickers(s, PAGES["sp500"])
    sp400 = tickers(s, PAGES["sp400"])
    if len(sp500) < 400 or len(sp400) < 300:
        raise SystemExit(f"Parse looks wrong (sp500={len(sp500)}, sp400={len(sp400)}) — aborting.")
    combined = list(dict.fromkeys(sp500 + sp400))

    body = [
        '"""Large-cap screening universe (S&P 500 + S&P 400 ≈ Russell 1000).',
        "",
        "AUTO-GENERATED by tools/refresh_universe.py — do not hand-edit.",
        f"S&P 500: {len(sp500)} · S&P 400: {len(sp400)} · combined unique: {len(combined)}.",
        '"""',
        "",
        "LARGE = [",
    ]
    for i in range(0, len(combined), 10):
        row = ", ".join(f'"{t}"' for t in combined[i:i + 10])
        body.append(f"    {row},")
    body.append("]")
    OUT.write_text("\n".join(body) + "\n")
    print(f"Wrote {len(combined)} tickers to {OUT}")


if __name__ == "__main__":
    main()
