#!/usr/bin/env python3
"""Regenerate the full list of US-listed common stocks.

Pulls the official Nasdaq Trader symbol directories (Nasdaq + NYSE/AMEX/other),
filters out ETFs, warrants, units, rights, preferreds and test issues, and
writes backend/all_us_symbols.py. This is the *raw* symbol set — the weekly
screen then applies a market-cap/price floor before doing any deep analysis.

    .venv/bin/python tools/refresh_symbols.py
"""
from __future__ import annotations

from pathlib import Path

from curl_cffi import requests as cr

NASDAQ = "https://www.nasdaqtrader.com/dynamic/symdir/nasdaqlisted.txt"
OTHER = "https://www.nasdaqtrader.com/dynamic/symdir/otherlisted.txt"
OUT = Path(__file__).resolve().parent.parent / "backend" / "all_us_symbols.py"

# Security-name substrings that mark a non-common-stock instrument.
JUNK_NAME = ("Warrant", "Unit", "Right", "Preferred", "Depositary", "Depository",
             " Notes", "% ", " ETF", " ETN", "Fund", " Trust ", "Acquisition")


def _clean(symbol: str, name: str, is_etf: str, is_test: str) -> str | None:
    if is_test.strip().upper() == "Y" or is_etf.strip().upper() == "Y":
        return None
    if any(w in name for w in JUNK_NAME):
        return None
    sym = symbol.strip().upper()
    if not sym or "$" in sym:
        return None
    sym = sym.replace(".", "-")            # class shares: BRK.A -> BRK-A (Yahoo)
    # Nasdaq 5-letter symbols ending in W/R/U/L are usually warrants/rights/units.
    if len(sym) == 5 and sym[-1] in "WRUL" and "-" not in sym:
        return None
    return sym


def main():
    s = cr.Session(impersonate="chrome")
    nd = s.get(NASDAQ, timeout=30).text.splitlines()
    ot = s.get(OTHER, timeout=30).text.splitlines()

    syms: list[str] = []
    # nasdaqlisted: Symbol|Name|MktCat|TestIssue|FinStatus|Lot|ETF|NextShares
    for ln in nd[1:]:
        p = ln.split("|")
        if len(p) < 8 or ln.startswith("File Creation"):
            continue
        c = _clean(p[0], p[1], p[6], p[3])
        if c:
            syms.append(c)
    # otherlisted: ACT Symbol|Name|Exchange|CQS Symbol|ETF|Lot|TestIssue|NASDAQ Symbol
    for ln in ot[1:]:
        p = ln.split("|")
        if len(p) < 7 or ln.startswith("File Creation"):
            continue
        c = _clean(p[0], p[1], p[4], p[6])
        if c:
            syms.append(c)

    syms = sorted(dict.fromkeys(syms))
    if len(syms) < 3000:
        raise SystemExit(f"Only parsed {len(syms)} symbols — source format may have changed.")

    body = [
        '"""All US-listed common stocks (Nasdaq + NYSE/AMEX).',
        "",
        "AUTO-GENERATED by tools/refresh_symbols.py — do not hand-edit.",
        f"Raw common-stock symbol set: {len(syms)} names (before any market-cap floor).",
        '"""',
        "",
        "ALL_US = [",
    ]
    for i in range(0, len(syms), 10):
        body.append("    " + ", ".join(f'"{t}"' for t in syms[i:i + 10]) + ",")
    body.append("]")
    OUT.write_text("\n".join(body) + "\n")
    print(f"Wrote {len(syms)} symbols to {OUT}")


if __name__ == "__main__":
    main()
